version: '2'
services:
  api:
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./api:/code
    env_file:
      env_dev.list
  node:
    command: npm start
    volumes:
      - ./frontend:/code
    env_file:
      env_dev.list
  db:
    env_file:
      env_dev.list
